### ISSUE TITLE
yarn dev - not working

### ISSUE THREAD

**Issue by AmirRezaei** [trendy-design/llmchat#44]
OS Windows 11.

git clone https://github.com/trendy-design/llmchat.git
cd llmchat
yarn install

yarn dev                                                                                                           
yarn run v1.22.22
$ next dev
  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000
  - Experiments (use with caution):
    · instrumentationHook

 ✓ Starting...
It looks like you're trying to use TypeScript but do not have the required package(s) installed.
Installing dependencies

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).

Installing devDependencies (yarn):
- typescript
- @types/react
- @types/node

[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["@types/react@18.3.4"] is trying to unpack in the same destination "C:\\Users\\itkom\\scoop\\apps\\yarn\\current\\cache\\v6\\npm-@types-react-18.3.4-dfdd534a1d081307144c00e325c06e00312c93a3-integrity\\node_modules\\@types\\react" as pattern ["@types/react@*","@types/react@*"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@types/node@22.5.1"] is trying to unpack in the same destination "C:\\Users\\itkom\\scoop\\apps\\yarn\\current\\cache\\v6\\npm-@types-node-22.5.1-de01dce265f6b99ed32b295962045d10b5b99560-integrity\\node_modules\\@types\\node" as pattern ["@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*","@types/node@*"]. This could result in non-deterministic behavior, skipping.
[3/4] Linking dependencies...
warning "@sentry/nextjs > @opentelemetry/instrumentation-http@0.52.1" has unmet peer dependency "@opentelemetry/api@^1.3.0".
warning "@sentry/nextjs > @sentry/opentelemetry@8.27.0" has unmet peer dependency "@opentelemetry/api@^1.9.0".
warning "@sentry/nextjs > @sentry/opentelemetry@8.27.0" has unmet peer dependency "@opentelemetry/core@^1.25.1".
warning "@sentry/nextjs > @sentry/opentelemetry@8.27.0" has unmet peer dependency "@opentelemetry/instrumentation@^0.52.1".
warning "@sentry/nextjs > @sentry/opentelemetry@8.27.0" has unmet peer dependency "@opentelemetry/sdk-trace-base@^1.25.1".
warning "@sentry/nextjs > @sentry/webpack-plugin@2.20.1" has unmet peer dependency "webpack@>=4.40.0".
warning "@sentry/nextjs > @opentelemetry/instrumentation-http > @opentelemetry/core@1.25.1" has unmet peer dependency "@opentelemetry/api@>=1.0.0 <1.10.0".
warning "@sentry/nextjs > @opentelemetry/instrumentation-http > @opentelemetry/instrumentation@0.52.1" has unmet peer dependency "@opentelemetry/api@^1.3.0".
warning " > @tiptap/extension-document@2.6.6" has unmet peer dependency "@tiptap/core@^2.6.6".
warning " > @tiptap/extension-hard-break@2.6.6" has unmet peer dependency "@tiptap/core@^2.6.6".
warning " > @tiptap/extension-highlight@2.6.6" has unmet peer dependency "@tiptap/core@^2.6.6".
warning " > @tiptap/extension-paragraph@2.6.6" has unmet peer dependency "@tiptap/core@^2.6.6".
warning " > @tiptap/extension-placeholder@2.6.6" has unmet peer dependency "@tiptap/core@^2.6.6".
warning " > @tiptap/extension-text@2.6.6" has unmet peer dependency "@tiptap/core@^2.6.6".
warning " > @tiptap/react@2.6.6" has unmet peer dependency "@tiptap/core@^2.6.6".
warning "@tiptap/react > @tiptap/extension-bubble-menu@2.6.6" has unmet peer dependency "@tiptap/core@^2.6.6".
warning "@tiptap/react > @tiptap/extension-floating-menu@2.6.6" has unmet peer dependency "@tiptap/core@^2.6.6".
warning "tiptap > tiptap-utils > prosemirror-utils@0.6.7" has incorrect peer dependency "prosemirror-tables@^0.6.5".
[4/4] Building fresh packages...
warning Error running install script for optional dependency: "R:\\llmchat\\node_modules\\canvas: Command failed.
Exit code: 7
Command: node-pre-gyp install --fallback-to-build --update-binary
Arguments:
Directory: R:\\llmchat\\node_modules\\canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@22.7.0 | win32 | x64
(node:20884) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@22.7.0 (node-v127 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack Error: spawn EINVAL
node-pre-gyp ERR! stack     at ChildProcess.spawn (node:internal/child_process:421:11)
node-pre-gyp ERR! stack     at Object.spawn (node:child_process:761:9)
node-pre-gyp ERR! stack     at module.exports.run_gyp (R:\\llmchat\\node_modules\\@mapbox\\node-pre-gyp\\lib\\util\\compile.js:80:18)
node-pre-gyp ERR! stack     at build (R:\\llmchat\\node_modules\\@mapbox\\node-pre-gyp\\lib\\build.js:41:13)
node-pre-gyp ERR! stack     at self.commands.<computed> [as build] (R:\\llmchat\\node_modules\\@mapbox\\node-pre-gyp\\lib\\node-pre-gyp.js:86:37)
node-pre-gyp ERR! stack     at run (R:\\llmchat\\node_modules\\@mapbox\\node-pre-gyp\\lib\\main.js:81:30)
node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
node-pre-gyp ERR! System Windows_NT 10.0.22631
node-pre-gyp ERR! command \"C:\\\\Users\\\\itkom\\\\scoop\\\\apps\\\\nodejs\\\\current\\\\node.exe\" \"R:\\\\llmchat\\\\node_modules\\\\@mapbox\\\\node-pre-gyp\\\\bin\\\\node-pre-gyp\" \"install\" \"--fallback-to-build\" \"--update-binary\"
node-pre-gyp ERR! cwd R:\\llmchat\\node_modules\\canvas
node-pre-gyp ERR! node -v v22.7.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11"
info This module is OPTIONAL, you can safely ignore this error
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
├─ @types/node@22.5.1
├─ @types/react@18.3.4
└─ typescript@5.5.4
info All dependencies
├─ @types/node@22.5.1
├─ @types/react@18.3.4
└─ typescript@5.5.4
$ husky

TypeError: Cannot read properties of undefined (reading 'endsWith')
    at mod.require (R:\llmchat\node_modules\next\dist\server\require-hook.js:62:17)
    at require (node:internal/modules/helpers:126:16)
    at verifyTypeScriptSetup (R:\llmchat\node_modules\next\dist\lib\verify-typescript-setup.js:116:42)
    at async verifyTypeScript (R:\llmchat\node_modules\next\dist\server\lib\router-utils\setup-dev-bundler.js:112:26)
    at async startWatcher (R:\llmchat\node_modules\next\dist\server\lib\router-utils\setup-dev-bundler.js:139:29)
    at async setupDevBundler (R:\llmchat\node_modules\next\dist\server\lib\router-utils\setup-dev-bundler.js:775:20)
    at async Span.traceAsyncFn (R:\llmchat\node_modules\next\dist\trace\trace.js:154:20)
    at async initialize (R:\llmchat\node_modules\next\dist\server\lib\router-server.js:78:30)
    at async Server.<anonymous> (R:\llmchat\node_modules\next\dist\server\lib\start-server.js:249:36)

Done in 8.58s.

**Comment by eriven** [comment]
Remove the **bun.lockb** file and try again.
